name: Increment Version on Push

on:
  push:
    branches:
      - main  # Change to your default branch name if it's different (e.g., 'master')

jobs:
  increment-version:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v2

      # Step 2: Increment the version number in the version.json file
      - name: Increment Version
        run: |
          # Read the current version from version.json, increment it, and write it back
          VERSION=$(jq '.version + 1' version.json)  # Increment the version
          jq ".version = $VERSION" version.json > temp.json && mv temp.json version.json

      # Step 3: Commit the updated version.json and push it back to the repository
      - name: Commit and Push Changes
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "GitHub Actions"
          git add version.json
          git commit -m "Increment version number"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
